baseURL = "https://crunchbang.github.io/"
languageCode = "en-us"
title = "Adventures with poorly tested code"
theme = "archie"

# Your Google analytics code.
googleAnalytics = "UA-165415128-1"

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    #subtitle = "Bug stories"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Books"
url = "/books"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/crunchbang"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hashb42"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/athul-suresh-572622147/"

# Enable tags.
[taxonomies]
   tag = "tags"